# OmegaConf config

jax:
  enable_x64: true

target:
  seed: 42

# Ensure artifacts root is stable across single runs and multiruns
store:
  root: runs

runtime:
  code_sha: ${git_sha:}
  hostname: ${hostname:}

# Training block (used by your ERM)
training:
  optimizer: adam
  learning_rate: 0.001
  steps: 5000
  early_stop_tol: 1e-6
  batch_size: null  # Use full batch by default

# Teacher configuration is loaded via config group defaults (teacher: _null)