# @package _global_.sampler
name: vi
vi:
  # Algorithm selection
  algo: mfa         # "mfa" (mixture of factor analyzers) or "flow"

  # Variational family
  M: 8              # number of mixture components
  r: 2              # rank budget per component

  # Optimization
  steps: 5000       # optimization steps
  batch_size: 256   # minibatch size
  lr: 0.01          # learning rate
  eval_every: 50    # how often to record metrics

  # Evaluation
  eval_samples: 64  # MC samples for final estimate

  # Precision
  dtype: float32
  use_whitening: true  # deprecated, use whitening_mode

  # Whitening (Stage 1)
  whitening_mode: none      # "none"|"rmsprop"|"adam" - geometry whitening
  whitening_decay: 0.99     # EMA decay for gradient moments

  # Stability (Stage 1)
  clip_global_norm: 5.0     # gradient clipping threshold (null to disable)
  alpha_temperature: 1.0    # softmax temperature on mixture weights

  # Diagnostics (Stage 2)
  tensorboard: false        # enable TensorBoard logging (requires tensorboardX)

  # Advanced Configuration (Stage 3)
  r_per_component: null     # heterogeneous rank budgets (list[int] of length M)
  alpha_dirichlet_prior: null  # Dirichlet(α) prior on mixture weights
  lr_schedule: null         # "cosine"|"linear_decay" learning rate schedule
  lr_warmup_frac: 0.05      # fraction of steps for warmup
  entropy_bonus: 0.0        # add λ * H(q) to ELBO for exploration
