# @package _global_.sampler
name: vi
vi:
  # Variational family (for future implementation)
  M: 8              # number of mixture components
  r: 2              # rank budget per component

  # Optimization
  steps: 5000       # optimization steps
  batch_size: 256   # minibatch size
  lr: 0.01          # learning rate
  eval_every: 50    # how often to record metrics

  # Posterior
  gamma: 0.001      # localizer strength (tune in {1e-4, 1e-3, 1e-2})

  # Evaluation
  eval_samples: 64  # MC samples for final estimate

  # Precision
  dtype: float32
  use_whitening: true
