# @package _global_.sampler
chains: 4

# Note: sgld_basic (BlackJAX reference implementation) uses the same config as sgld
sgld:
  # reach ~20k FGEs (1436000 steps * (256/20000) = 20000 FGEs)
  # steps: 1436000
  steps: 3000000
  warmup: 0
  batch_size: 1024
  step_size: 0.00000025
  dtype: float32
  precond: rmsprop
  beta1: 0.9
  beta2: 0.999
  eps: 0.00000001
  bias_correction: true
  # Increased thinning due to large step count
  eval_every: 100

hmc:
  # ~40k FGEs (2000 draws * 10 steps = 10000 FGEs) but actually our acceptance is low so more like 20k
  # draws: 4000
  draws: 8000
  warmup: 200
  num_integration_steps: 10
  step_size: 0.01
  dtype: float64
  adapt_step_size: true
  target_acceptance: 0.8

mclmc:
  # ~40k FGEs (4000 draws * (1.0/0.1) = 10000 FGEs) but actually our acceptance is low so more like 20k
  # draws: 4000
  draws: 8000
  L: 1.0
  step_size: 0.1
  dtype: float64
  diagonal_preconditioning: false
  num_steps: 500
  frac_tune1: 0.1
  frac_tune2: 0.1
  frac_tune3: 0.1
  desired_energy_var: 0.0005
  trust_in_estimate: 1.0
  num_effective_samples: 150.0
  integrator: isokinetic_mclachlan