# Two-stage: Stage B (sample) — OmegaConf-only (no Hydra defaults)

jax:
  enable_x64: true

# Ensure artifacts root is stable across single runs and multiruns
store:
  root: runs

# Target selection is provided via CLI (--target-id). Keep this file agnostic.

runtime:
  seed: 12345  # used to split per-chain keys downstream
  code_sha: ${git_sha:}

sampler:
  chains: 4

posterior:
  loss: mse
  beta_mode: 1_over_log_n
  beta0: 1.0
  prior_radius: null
  gamma: 1.0
