# conf/hydra/launcher/submitit_slurm.yaml
# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

# Directory for SLURM logs (relative to the Hydra sweep output directory)
submitit_folder: ${hydra.sweep.dir}/.submitit_slurm

# Job timeout in minutes
timeout_min: 119

# Resources requested per task (job)
cpus_per_task: 1
mem_gb: 64
gpus_per_node: 1

# SLURM partition (Unused on my cluster)
partition: null

# Limit concurrent jobs to avoid overwhelming the scheduler
array_parallelism: 256

additional_parameters:
  account: null
