# lambda_hat/conf/workflow.yaml
# @package _global_

# Unified Workflow Configuration for N x M Sweeps

# NOTE: This file is consumed via OmegaConf mergers from the Snakefile 

# --- Shared Config ---
jax:
  enable_x64: true

# Ensure artifacts root is stable across single runs and multiruns
store:
  root: runs

runtime:
  seed: 12345  # Used for sampler PRNG splitting (Stage B Seed)
  code_sha: ${git_sha:}
  hostname: ${hostname:}

# --- Stage A: Target Definition (Used for Fingerprinting) ---
target:
  # Seed for data generation and NN training (Stage A Seed)
  seed: 42

# --- Stage B: Sampler Configuration ---
sampler:
  chains: 4
  # name will be overridden by sample/sampler group

posterior:
  # Defaults compatible with existing structure
  loss: mse
  beta_mode: 1_over_log_n
  beta0: 1.0
  gamma: 1.0

# Training block (used for Stage A target building)
training:
  optimizer: adam
  learning_rate: 0.001
  steps: 5000
  early_stop_tol: 1e-6
  batch_size: null  # Use full batch by default

# Teacher configuration is loaded via config group defaults (teacher: _null)

# --- Dynamic Target ID Resolution ---
# Target ID will be passed from Snakemake